[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"sweet.core.system" = ["*.json"]
"sweet.resource.graphics.passes" = ["*"]
"sweet.resource.assets.defaults" = ["*"]

[project]
name = "sweet"
version = "0.1.0"
description = "Game Development Module"
authors = [
    { name = "Isaque-Ias" },
    { name = "DelNailo" },
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    # Setup
    "setuptools>=61.0.0",
    "colorama>=0.4.6",

    # Rendering
    "moderngl>=5.12.0",
    "moderngl-window>=3.1.1",
    "pyopengl==3.1.10",
    "glfw==2.10.0",

    # Data
    "numpy>=2.1.0",
    "pyglm>=2.8.3",

    # Mesh processing
    "trimesh>=4.7.0",

    # glTF
    "pygltflib>=1.16.0",

    # Images
    "pillow>=10.4.0",

    # Computer Vision
    "opencv-python>=4.10.0.0",
]