from enum import Enum

class Key(Enum):
    UNDEFINED = ...
    A = ...
    B = ...
    C = ...
    SPACE = ...
    ESCAPE = ...
    CAPS_LOCK = ...

class MouseButton(Enum):
    UNDEFINED = ...
    LEFT = ...
    RIGHT = ...
    MIDDLE = ...

class GamepadButton(Enum):
    UNDEFINED = ...
    A = ...
    B = ...
    X = ...
    Y = ...
