from .vector import VectorLike, Vec3
from enum import Enum

class RotationModel(Enum):
    EULER_XYZ = ...
    EULER_ZYX = ...
    QUATERNION = ...
    VECTOR = ...

class Rotation:
    values: VectorLike
    model: RotationModel

    def __init__(self, values: VectorLike = Vec3(), model: RotationModel = RotationModel.VECTOR) -> None: ...

    def convert(self, model: RotationModel) -> "Rotation": ...