from enum import Enum
from .vector import Vec3, Vec4
from typing import Any, overload, Sequence
from abc import ABC

class RotationModel(Enum):
    EULER_XYZ = ...
    EULER_ZYX = ...
    QUATERNION = ...
    VECTOR = ...

class Rotation(ABC):
    def convert(self, target_model: RotationModel) -> Any: ...

class QuaternionAngle(Vec4, Rotation):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, scalar: float, /) -> None: ...

    @overload
    def __init__(self, x: float, y: float, z: float, w: float, /) -> None: ...

    @overload
    def __init__(self, iterable: Sequence[float], /) -> None: ...

    def __init__(self, *args: Any) -> None: ...

    def to_vector(self) -> VectorAngle: ...

    def to_euler_xyz(self) -> EulerAngleXYZ: ...

    def to_euler_zyx(self) -> EulerAngleZYX: ...

    def convert(self, target_model: RotationModel) -> Any: ...

class VectorAngle(Vec3, Rotation):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, scalar: float, /) -> None: ...

    @overload
    def __init__(self, x: float, y: float, z: float, /) -> None: ...

    @overload
    def __init__(self, iterable: Sequence[float], /) -> None: ...

    def __init__(self, *args: Any) -> None: ...

    def to_quaternion(self) -> QuaternionAngle: ...

    def to_euler_xyz(self) -> EulerAngleXYZ: ...

    def to_euler_zyx(self) -> EulerAngleZYX: ...

    def convert(self, target_model: RotationModel) -> Any: ...

class EulerAngleXYZ(Vec3, Rotation):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, scalar: float, /) -> None: ...

    @overload
    def __init__(self, x: float, y: float, z: float, /) -> None: ...

    @overload
    def __init__(self, iterable: Sequence[float], /) -> None: ...

    def __init__(self, *args: Any) -> None: ...

    def to_euler_zyx(self) -> EulerAngleZYX: ...

    def to_quaternion(self) -> QuaternionAngle: ...

    def to_vector(self) -> VectorAngle: ...

    def convert(self, target_model: RotationModel) -> Any: ...

class EulerAngleZYX(Vec3, Rotation):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, scalar: float, /) -> None: ...

    @overload
    def __init__(self, x: float, y: float, z: float, /) -> None: ...

    @overload
    def __init__(self, iterable: Sequence[float], /) -> None: ...

    def __init__(self, *args: Any) -> None: ...

    def to_euler_xyz(self) -> EulerAngleXYZ: ...

    def to_quaternion(self) -> QuaternionAngle: ...

    def to_vector(self) -> VectorAngle: ...

    def convert(self, target_model: RotationModel) -> Any: ...