from abc import ABC
from collections.abc import Iterable, Iterator, Sequence
from typing import Union

from typing import Self

VectorLike = Union[Vec, Sequence[float | int]]

class Vec(ABC):
    scalars: list[float]

    def __init__(self, values: Sequence[float], /) -> None: ...

    @classmethod
    def from_iter(cls, values: Iterable[float]) -> Self: ...

    @property
    def dim(self) -> int: ...

    def magnitude(self) -> float: ...
    def magnitude_squared(self) -> float: ...
    def normalize(self) -> Self: ...
    def dot(self, other: VectorLike) -> float: ...
    def floor(self) -> Self: ...
    def round(self) -> Self: ...
    def min(self, value: float) -> Self: ...
    def max(self, value: float) -> Self: ...
    def clamp(self, minimum: float, maximum: float) -> Self: ...
    def lerp(self, other: VectorLike, t: float) -> Self: ...

    def __add__(self, other: VectorLike) -> Self: ...
    def __sub__(self, other: VectorLike) -> Self: ...
    def __neg__(self) -> Self: ...
    def __mul__(self, other: float) -> Self: ...
    def __rmul__(self, other: float) -> Self: ...
    def __truediv__(self, other: float) -> Self: ...
    def __floordiv__(self, other: float) -> Self: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def unp(self) -> tuple[float, ...]: ...

class VecN(Vec): ...

class Vec2(Vec):
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...

    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, val: float) -> None: ...

    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, val: float) -> None: ...

    def angle(self) -> float: ...
    def rotate(self, angle_deg: float) -> Vec2: ...
    def rotate90(self) -> Vec2: ...
    def cross(self, other: VectorLike) -> float: ...
    def mirror_x(self) -> Vec2: ...
    def mirror_y(self) -> Vec2: ...

class Vec3(Vec):
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...

    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, val: float) -> None: ...

    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, val: float) -> None: ...

    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, val: float) -> None: ...

    def direction(self) -> Vec3: ...
    def cross(self, other: VectorLike) -> Vec3: ...

class Vec4(Vec):
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 0.0) -> None: ...

    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, val: float) -> None: ...

    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, val: float) -> None: ...

    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, val: float) -> None: ...

    @property
    def w(self) -> float: ...
    @w.setter
    def w(self, val: float) -> None: ...